version: '3.8'

networks:
  brewery-network:
    driver: bridge

services:
  brewery_db:
    image: postgres:15
    container_name: brewery_db
    environment:
      POSTGRES_DB: brewery_lims
      POSTGRES_USER: brewery_admin
      POSTGRES_PASSWORD: brewery_secret
    ports:
      - "5432:5432"
    networks:
      - brewery-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: